FROM node:20-alpine AS build
WORKDIR /app
ENV NODE_OPTIONS="--max-old-space-size=4096"
COPY frontend/package*.json ./
RUN npm config set fund false && npm config set audit false
RUN npm install --loglevel=error

COPY frontend/. .
RUN npm run build

FROM nginx:stable-alpine
COPY --from=build /app/build /usr/share/nginx/html
EXPOSE 80
CMD ['nginx', '-g', 'daemon off;']